# Generated by Django 3.1.6 on 2021-02-26 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_exam_option5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('exam_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.exam')),
                ('Name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
            bases=('quiz.exam',),
        ),
    ]
